export const INTERVALL_TEMPLATES = [
  {
    id: 'rask-intervall-400m',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: 'Fast interval – 400m',
    description: '15 x 400 meters @ 12 km/h / 5:00 pace, 1 min rest',
    distance: '9 km',
    sessionDetails: '15 x 400 meters @ 12 km/h / 5:00 pace with 1 min rest between reps.',
    warmup: '2 km easy warmup (up: 2, down: 1)',
    cooldown: '1 km cooldown',
    intensityZone: 4,
    notes: 'Focus: fast interval session',
  },
  {
    id: '45-15-3x10',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: '45/15 – 3x10',
    description: '45/15 3x10: start at 11 km/h, increase by 0.1 every second rep',
    sessionDetails: '3 sets of 10 reps at 45 sec work / 15 sec rest. Start at 11 km/h and increase by 0.1 km/h every second rep.',
    warmup: '2 km easy warmup',
    intensityZone: 4,
    notes: '1 min: 10 x 1 min @ 13 km/h, 3 min rest',
  },
  {
    id: '1min-x10-13kmt',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: 'Fast interval – 1min x10',
    description: '10 x 1 min @ 13 km/h, 3 min rest',
    sessionDetails: '10 x 1 min @ 13 km/h with 3 min rest between reps.',
    warmup: '2 km easy warmup',
    intensityZone: 4,
    notes: 'Feel free to push the pace here',
  },
  {
    id: '200m-sprint',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: '200m sprint',
    description: '15 x 200 meters @ start at 13 km/h, can increase from there',
    sessionDetails: '15 x 200 meters. Start at 13 km/h and increase if you are in control.',
    warmup: '2 km easy warmup',
    intensityZone: 4,
  },
  {
    id: 'hardt-5x4min',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: 'Hard – 5x4 min',
    description: '5 x 4 min in zone 4-5, 2 min rest',
    sessionDetails: '5 x 4 min hard in zone 4-5 with 2 min rest between reps.',
    warmup: '2 km easy warmup',
    cooldown: '1 km easy cooldown',
    intensityZone: [4, 5],
  },
]
