export const INTERVALL_TEMPLATES = [
  {
    id: 'rask-intervall-400m',
    category: 'Intervall',
    type: 'interval',
    activityTag: 'run',
    title: 'Rask intervall – 400m',
    description: '15 x 400 meter @ 12 km/t / 5:00 pace, 1 min pause',
    distance: '9 km',
    sessionDetails: '15 x 400 meter @ 12 km/t / 5:00 pace med 1 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming (opp: 2, ned: 1)',
    cooldown: '1 km nedkjøling',
    intensityZone: 4,
    notes: 'Aktfokus: rask intervallakt',
  },
  {
    id: '45-15-3x10',
    category: 'Intervall',
    type: 'interval',
    activityTag: 'run',
    title: '45/15 – 3x10',
    description: '45/15 3x10: starte på 11 km/t, øke med 0.1 for hvert andre drag',
    sessionDetails: '3 sett med 10 drag på 45 sek arbeid / 15 sek pause. Start på 11 km/t og øk med 0.1 km/t for hvert andre drag.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
    notes: '1 min: 10 x 1 min @ 13 km/t, 3 min pause',
  },
  {
    id: '1min-x10-13kmt',
    category: 'Intervall',
    type: 'interval',
    activityTag: 'run',
    title: 'Rask intervall – 1min x10',
    description: '10 x 1 min @ 13 km/t, 3 min pause',
    sessionDetails: '10 x 1 min @ 13 km/t med 3 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
    notes: 'Her er det lov å dra på ganske bra',
  },
  {
    id: '200m-sprint',
    category: 'Intervall',
    type: 'interval',
    activityTag: 'run',
    title: '200m sprint',
    description: '15 x 200 meter @ start på 13 km/t, kan øke deretter',
    sessionDetails: '15 x 200 meter. Start på 13 km/t og øk dersom du har kontroll.',
    warmup: '2 km rolig oppvarming',
    intensityZone: 4,
  },
  {
    id: 'hardt-5x4min',
    category: 'Intervall',
    type: 'interval',
    activityTag: 'run',
    title: 'Hardt – 5x4 min',
    description: '5 x 4 min i sone 4-5, 2 min pause',
    sessionDetails: '5 x 4 min hardt i sone 4-5 med 2 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming',
    cooldown: '1 km rolig nedjogg',
    intensityZone: [4, 5],
  },
]
