export const ROLIG_TEMPLATES = [
  {
    id: 'rolig ',
    category: 'Easy',
    type: 'rolig',
    activityTag: 'run',
    title: 'Easy jog',
    description: 'Easy jog, zone 1–2',
    sessionDetails: 'Easy jog in zone 1-2. Stay at conversational pace throughout.',
    intensityZone: [1, 2],
  },
  {
    id: 'rolig langtur',
    category: 'Easy',
    type: 'rolig',
    activityTag: 'run',
    title: 'Easy run – 6km',
    description: 'Zone 1–2 easy 10 km',
    distance: '6 km',
    sessionDetails: 'Easy running in zone 1-2 over 10 km.',
    intensityZone: [1, 2],
  },
  {
    id: 'kontinuerlig tempo',
    category: 'Easy',
    type: 'terskel',
    activityTag: 'run',
    title: 'Continuous tempo',
    description: '30 min continuous. Start at 9 km/h, increase gradually. Start in low zone 3, finish in low/moderate zone 4.',
    sessionDetails: '30 min continuous on treadmill. Start at 9 km/h and increase gradually. Start in low zone 3 and finish in low/moderate zone 4.',
    intensityZone: [3, 4],
  },
]
