export const STYRKE_TEMPLATES = [
  {
    id: 'molle-styrke-fullkropp',
    category: 'Mølle + styrke',
    type: 'molle',
    activityTag: 'run',
    title: 'Mølle + styrke (fullkropp)',
    description: '30 min gå mølle motbakke + styrke (fullkropp)',
    sessionDetails: '30 min gåing i motbakke på mølle før styrkedelen.',
    intensityZone: 2,
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk 3 x 8\nSittende roing 3 x 8\nBrystpress 3 x 8\nSkulderhev 3 x 10\nMage 3 x 8',
    rest: '60-90 sek mellom sett',
    notes: 'Fullkropp med obligatoriske baseovelser for hele kroppen.',
  },
  {
    id: 'styrke-overkropp',
    category: 'Styrke',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Styrke – overkropp',
    description: 'Nedtrekk (apparat) 8x3\nBrystpress (apparat) 8x3\nSittende roing (apparat) 3x8\nSkulderpress 3x8\nTricep extension (apparat) 3x8',
    warmup: '30 min gå motbakke',
    exercises: 'Nedtrekk (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nSkulderpress 3 x 8\nTricep extension (apparat) 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-underkropp',
    category: 'Styrke',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Styrke – underkropp',
    description: 'Leg extension 8–12x3\nSittende leg curl 8x3\nKnebøy 8x3\nMarkløft 8x3\nHip trust 8x3\nTå hev 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nSittende leg curl 3 x 8\nKnebøy 3 x 8\nMarkløft 3 x 8\nHip thrust 3 x 8\nTåhev 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-fullkropp',
    category: 'Styrke',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Styrke – fullkropp A',
    description: 'Leg extension 8–12x3\nKnebøy 8x3\nHip trust 8x3\nNedtrekk (apparat) 8x3\nSittende roing (apparat) 3x8\nBrystpress (apparat) 8x3\nSkulderhev 3x10\nMarkløft 8x3\nSittende leg curl 8x3\nTricep extension (apparat) 3x8',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSkulderhev 3 x 10\nMarkløft 3 x 8\nSittende leg curl 3 x 8\nTricep extension (apparat) 3 x 8',
    rest: '60-90 sek mellom sett',
  },
  {
    id: 'styrke-fullkropp-b',
    category: 'Styrke',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Styrke – fullkropp B',
    description: 'Leg extension 8–12x3\nKnebøy 8x3\nHip trust 8x3\nNedtrekk (apparat) 8x3\nSittende roing (apparat) 8x3\nBrystpress (apparat) 8x3\nSkulderhev 3x10\nRumensk markløft 8x3\nUtfall 8x3 per bein\nSittende leg curl 8x3',
    warmup: '30 min gå motbakke',
    exercises: 'Leg extension 3 x 8-12\nKnebøy 3 x 8\nHip trust 3 x 8\nNedtrekk (apparat) 3 x 8\nSittende roing (apparat) 3 x 8\nBrystpress (apparat) 3 x 8\nSkulderhev 3 x 10\nRumensk markløft 3 x 8\nUtfall 3 x 8 per bein\nSittende leg curl 3 x 8',
    rest: '60-90 sek mellom sett',
  },
]
