export const STYRKE_TEMPLATES = [
  {
    id: 'molle-styrke-fullkropp',
    category: 'Easy',
    type: 'molle',
    activityTag: 'run',
    title: 'Treadmill + strength (full body)',
    description: '30 min walking treadmill incline + strength (full body)',
    sessionDetails: '30 min walking on treadmill incline before the strength portion.',
    intensityZone: 2,
    warmup: '30 min walking incline',
    exercises: 'Leg extension 3 x 8-12\nSquat 3 x 8\nHip thrust 3 x 8\nLat pulldown 3 x 8\nSeated row 3 x 8\nChest press 3 x 8\nShoulder raise 3 x 10\nCore 3 x 8',
    rest: '60-90 sec between sets',
    notes: 'Full body with mandatory base exercises for the whole body.',
  },
  {
    id: 'styrke-overkropp',
    category: 'Easy',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Strength – upper body',
    description: 'Lat pulldown (machine) 8x3\nChest press (machine) 8x3\nSeated row (machine) 3x8\nShoulder press 3x8\nTricep extension (machine) 3x8',
    warmup: '30 min walking incline',
    exercises: 'Lat pulldown (machine) 3 x 8\nChest press (machine) 3 x 8\nSeated row (machine) 3 x 8\nShoulder press 3 x 8\nTricep extension (machine) 3 x 8',
    rest: '60-90 sec between sets',
  },
  {
    id: 'styrke-underkropp',
    category: 'Easy',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Strength – lower body',
    description: 'Leg extension 8–12x3\nSeated leg curl 8x3\nSquat 8x3\nDeadlift 8x3\nHip thrust 8x3\nCalf raise 8x3',
    warmup: '30 min walking incline',
    exercises: 'Leg extension 3 x 8-12\nSeated leg curl 3 x 8\nSquat 3 x 8\nDeadlift 3 x 8\nHip thrust 3 x 8\nCalf raise 3 x 8',
    rest: '60-90 sec between sets',
  },
  {
    id: 'styrke-fullkropp',
    category: 'Easy',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Strength – full body A',
    description: 'Leg extension 8–12x3\nSquat 8x3\nHip thrust 8x3\nLat pulldown (machine) 8x3\nSeated row (machine) 3x8\nChest press (machine) 8x3\nShoulder raise 3x10\nDeadlift 8x3\nSeated leg curl 8x3\nTricep extension (machine) 3x8',
    warmup: '30 min walking incline',
    exercises: 'Leg extension 3 x 8-12\nSquat 3 x 8\nHip thrust 3 x 8\nLat pulldown (machine) 3 x 8\nSeated row (machine) 3 x 8\nChest press (machine) 3 x 8\nShoulder raise 3 x 10\nDeadlift 3 x 8\nSeated leg curl 3 x 8\nTricep extension (machine) 3 x 8',
    rest: '60-90 sec between sets',
  },
  {
    id: 'styrke-fullkropp-b',
    category: 'Easy',
    type: 'styrke',
    activityTag: 'strength',
    title: 'Strength – full body B',
    description: 'Leg extension 8–12x3\nSquat 8x3\nHip thrust 8x3\nLat pulldown (machine) 8x3\nSeated row (machine) 8x3\nChest press (machine) 8x3\nShoulder raise 3x10\nRomanian deadlift 8x3\nLunges 8x3 per leg\nSeated leg curl 8x3',
    warmup: '30 min walking incline',
    exercises: 'Leg extension 3 x 8-12\nSquat 3 x 8\nHip thrust 3 x 8\nLat pulldown (machine) 3 x 8\nSeated row (machine) 3 x 8\nChest press (machine) 3 x 8\nShoulder raise 3 x 10\nRomanian deadlift 3 x 8\nLunges 3 x 8 per leg\nSeated leg curl 3 x 8',
    rest: '60-90 sec between sets',
  },
]
