export const TERSKEL_TEMPLATES = [
  {
    id: 'hard-4x1km',
    category: 'Hard',
    type: 'interval',
    activityTag: 'run',
    title: 'hard – 4x1km',
    description: '4 x 1km @ 11.5 km/h / 5:15 pace, 2 min rest',
    distance: '7 km',
    sessionDetails: '4 x 1 km @ 11.5 km/h / 5:15 pace with 2 min rest.',
    warmup: 'up: 2, down: 1, total: 7',
    intensityZone: [4, 5],
  },
  {
    id: 'terskel-3x2km',
    category: 'Hard',
    type: 'terskel',
    activityTag: 'run',
    title: 'Threshold – 3x2km',
    description: '3x2 km @ 9.5–10.5 km/h / 6:00 pace, 2 min rest',
    distance: '9 km',
    sessionDetails: '3 x 2 km @ 9.5–10.5 km/h / 6:00 pace with 2 min rest.',
    intensityZone: 4,
  },
  {
    id: 'terskel-4x2km',
    category: 'Hard',
    type: 'terskel',
    activityTag: 'run',
    title: 'Threshold – 4x2km',
    description: '4 x 2 km @ 9–10 km/h, 2 min rest',
    distance: '11 km',
    sessionDetails: '4 x 2 km @ 9–10 km/h with 2 min rest.',
    intensityZone: 4,
  },
  {
    id: 'terskel-5x6min',
    category: 'Hard',
    type: 'terskel',
    activityTag: 'run',
    title: 'Threshold – 5x6 min',
    description: '5 x 6 min in zone 3, 1 min rest',
    sessionDetails: '5 x 6 min in zone 3 with 1 min rest between reps.',
    warmup: '2 km easy warmup',
    cooldown: '1 km easy cooldown',
    intensityZone: 3,
  },
]
