export const TERSKEL_TEMPLATES = [
  {
    id: 'hard-4x1km',
    category: 'interval',
    type: 'interval',
    activityTag: 'run',
    title: 'hard – 4x1km',
    description: '4 x 1km @ 11.5 km/t / 5:15 pace, 2 min pause',
    distance: '7 km',
    sessionDetails: '4 x 1 km @ 11.5 km/t / 5:15 pace med 2 min pause.',
    warmup: 'opp: 2, ned: 1, tot: 7',
    intensityZone: [4, 5],
  },
  {
    id: 'terskel-3x2km',
    category: 'Terskel',
    type: 'terskel',
    activityTag: 'run',
    title: 'Terskel – 3x2km',
    description: '3x2 km @ 9.5–10.5 km/t / 6:00 pace, 2 min pause',
    distance: '9 km',
    sessionDetails: '3 x 2 km @ 9.5–10.5 km/t / 6:00 pace med 2 min pause.',
    intensityZone: 4,
  },
  {
    id: 'terskel-4x2km',
    category: 'Terskel',
    type: 'terskel',
    activityTag: 'run',
    title: 'Terskel – 4x2km',
    description: '4 x 2 km @ 9–10 km/t, 2 min pause',
    distance: '11 km',
    sessionDetails: '4 x 2 km @ 9–10 km/t med 2 min pause.',
    intensityZone: 4,
  },
  {
    id: 'terskel-5x6min',
    category: 'Terskel',
    type: 'terskel',
    activityTag: 'run',
    title: 'Terskel – 5x6 min',
    description: '5 x 6 min i sone 3, 1 min pause',
    sessionDetails: '5 x 6 min i sone 3 med 1 min pause mellom dragene.',
    warmup: '2 km rolig oppvarming',
    cooldown: '1 km rolig nedjogg',
    intensityZone: 3,
  },
]
